import streamlit as st
import dns.resolver
import socket
import time

st.set_page_config(page_title="Email Health Tool", page_icon="✉️")

# --- HEADER ---
domain = st.text_input("Enter the domain to audit", value="", placeholder="example.com")
if domain:
    st.title(f"🔍 Auditing: {domain}")
else:
    st.title("✉️ Email Health Audit Tool")

# DNS Setup
resolver = dns.resolver.Resolver()
resolver.nameservers = ['8.8.8.8', '8.8.4.4']
resolver.timeout = 5
resolver.lifetime = 5

def robust_query(query_domain, record_type):
    for _ in range(3):
        try:
            return resolver.resolve(query_domain, record_type)
        except:
            time.sleep(0.5)
            continue
    return None

if st.button("Start Full Audit"):
    if domain:
        with st.spinner('🛠️ Analyzing Records...'):
            time.sleep(1.2)
            
            # 1. Variables
            spf_s, dmarc_s, mx_s, dkim_s, black_s = False, False, False, False, True 
            ip_display = "N/A"

            # 2. Columns
            c1, c2 = st.columns(2)
            
            with c1:
                st.subheader("🛡️ Authentication")
                
                # MX Check
                mx_r = robust_query(domain, 'MX')
                if mx_r:
                    st.success(f"✅ MX Found: {mx_r[0].exchange}")
                    mx_s = True
                
                # SPF Check
                txt_r = robust_query(domain, 'TXT')
                if txt_r:
                    spf_find = [r.to_text() for r in txt_r if "v=spf1" in r.to_text()]
                    if spf_find:
                        st.success(f"✅ SPF Found: {spf_find[0][:50]}...")
                        spf_s = True
                
                # DMARC Check
                dm_r = robust_query(f"_dmarc.{domain}", 'TXT')
                if dm_r:
                    st.success(f"✅ DMARC Found: {dm_r[0].to_text()[:50]}...")
                    dmarc_s = True

                # DKIM Check
                for sel in ['google', 'default', 'k1', 'smtp']:
                    dk_r = robust_query(f"{sel}._domainkey.{domain}", 'TXT')
                    if dk_r:
                        st.success(f"✅ DKIM Found ({sel})")
                        dkim_s = True
                        break
                if not dkim_s:
                    st.info("ℹ️ DKIM: No common selector found")

            with c2:
                st.subheader("🚩 Reputation")
                try:
                    ip_display = socket.gethostbyname(domain)
                    st.info(f"Domain IP: {ip_display}")
                    
                    rev = ".".join(reversed(ip_display.split(".")))
                    try:
                        resolver.resolve(f"{rev}.zen.spamhaus.org", 'A')
                        st.error("⚠️ ALERT: IP is Blacklisted!")
                        black_s = False
                    except:
                        st.success("✅ IP is not listed on Spamhaus.")
                except:
                    st.error("Could not resolve IP address.")

            # 3. Score
            st.divider()
            score = sum([mx_s, spf_s, dmarc_s, dkim_s, black_s]) * 20
            s_color = "#28a745" if score >= 80 else "#ffc107" if score >= 60 else "#dc3545"
            
            st.subheader(f"📊 Health Score: {score}/100")
            if score >= 80: st.balloons()

            # 4. Colorful Report for Download
            report_html = f"""
            <div style="font-family: Arial; border: 8px solid {s_color}; padding: 25px; border-radius: 15px;">
                <h2 style="color: {s_color};">Email Health Audit Report</h2>
                <p><b>Domain:</b> {domain} | <b>IP:</b> {ip_display}</p>
                <hr>
                <div style="font-size: 18px;">
                    <p>{'✅' if mx_s else '❌'} MX Record</p>
                    <p>{'✅' if spf_s else '❌'} SPF Record</p>
                    <p>{'✅' if dmarc_s else '❌'} DMARC Record</p>
                    <p>{'✅' if dkim_s else '❌'} DKIM Record</p>
                    <p>{'✅' if black_s else '❌'} Clean Reputation</p>
                </div>
                <h3 style="color: {s_color};">Final Score: {score}/100</h3>
                <p style="font-size: 12px; color: grey;">Generated by Email Solution Pro</p>
            </div>
            """

            st.download_button(
                label="📥 Download Colorful Report",
                data=report_html,
                file_name=f"Audit_{domain}.html",
                mime="text/html"
            )
    else:
        st.info("Please enter a domain name.")